moviesite/main_moviesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls'))
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moviesite/movies/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.MovieView.as_view()),
    path("filter/", views.FilterMoviesView.as_view(), name='filter'),
    path("search/", views.Search.as_view(), name='search'),
    path("add-rating/", views.AddRating.as_view(), name='add_rating'),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name="movie_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("person/<str:slug>/", views.PersonView.as_view(), name="person_detail"),

]

moviesite/movies/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime
from django.db import connection

from django.urls import reverse


class Category(models.Model):
    """"
    Таблица категорий Category содержит информацию о категории
    произведения - фильм, мультфильм, сериал...
    """
    name = models.CharField("Категория", max_length=50)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Genre(models.Model):
    """"
    Таблица жанров Genre содержит информацию о жанре
    фильма - мелодрама, детектив, ужасы...
    """
    name = models.CharField("Название", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Person(models.Model):
    """
    Таблица с информацией о людях Person
    Содержит данные об актерах, режисерах и прочих людях, принимающих
    участие в съемочном процессе
    """
    name = models.CharField("Имя", max_length=100)
    birthdate = models.DateField("Дата рождения", default=datetime.now().day)
    biography = models.TextField("Краткая биография")
    image = models.ImageField("Изображение", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("person_detail", kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Участник съемочного процесса"
        verbose_name_plural = "Участники съемочного процесса"


class Movie(models.Model):
    """
    Таблица с информацией о фильмах Movie
    Содержит данные о фильмах - название, категория, жанр, актеры, режисеры...
    """
    name = models.CharField("Название", max_length=100)
    year = models.PositiveSmallIntegerField("Год", default=datetime.now().year)
    country = models.CharField("Страна", max_length=50)
    poster = models.ImageField("Постер", upload_to="movies/")
    tagline = models.CharField("Слоган", max_length=100, default='')
    synopsis = models.TextField("Синопсис")
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    directors = models.ManyToManyField(Person, verbose_name="режиссер", related_name="film_director")
    actors = models.ManyToManyField(Person, verbose_name="актеры", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    world_premiere = models.DateField("Примьера в мире", default=datetime.now().day)
    budget = models.PositiveIntegerField("Бюджет", default=0)
    fees_in_usa = models.PositiveIntegerField("Сборы в США", default=0)
    fess_in_world = models.PositiveIntegerField("Сборы в мире", default=0)
    url = models.SlugField(max_length=130, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingValue(models.Model):
    """Значение рейтинга"""
    value = models.SmallIntegerField("Значение рейтинга", default=0)

    def __str__(self):
        return f"{self.value}"

    class Meta:
        verbose_name = "Значение рейтинга"
        verbose_name_plural = "Значение рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)
    value = models.ForeignKey(RatingValue, verbose_name="Значение", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} - {self.movie} - {self.value}"

    def averageRating(movie_id):
        cursor = connection.cursor()
        cursor.execute("""with rating as (
  select case when sum(distinct rv.value) is not null then sum(rv.value) else 0 end as rating,
    case when sum(distinct rv.value) is not null then count(rv.value) else 0 end as rating_count
  from movies_movie movie
  inner join movies_rating mr on movie.id = mr.movie_id
  inner join movies_ratingvalue rv on rv.id = mr.value_id
    where movie.id = %s
),
reviews_rating as (
  select case when sum(distinct rv.value) is not null then sum(rv.value) else 0 end as rating,
    case when sum(distinct rv.value) is not null then count(rv.value) else 0 end as rating_count
  from movies_movie movie
  inner join movies_reviews mr on movie.id = mr.movie_id
  inner join movies_reviewtypes rt on rt.id = mr.type_id
  inner join movies_ratingvalue rv on rv.id = rt.rating_id
    where movie.id = %s
)
select
  round(((cast(rating.rating + reviews_rating.rating as float))/(cast(rating.rating_count + reviews_rating.rating_count as float))),2) as awarage_rating
from reviews_rating
cross join rating""", [movie_id, movie_id])
        row = cursor.fetchone()[0]
        return row

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинг"


class ReviewTypes(models.Model):
    """Типы отзыва к фильму"""
    name = models.CharField("Тип", max_length=50)
    code = models.CharField("Код", max_length=50)
    color = models.CharField("Код", max_length=20)
    rating = models.ForeignKey(RatingValue, verbose_name="Рейтинг", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Типы отзыва к фильму"
        verbose_name_plural = "Типы отзыва к фильму"


class Reviews(models.Model):
    """Отзывы к фильму"""
    type = models.ForeignKey(ReviewTypes, verbose_name="Тип", on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    text = models.TextField("Комментарий")

    def __str__(self):
        return f"{self.movie}"

    class Meta:
        verbose_name = "Отзывы к фильму"
        verbose_name_plural = "Отзывы к фильму"


class MovieRatingView(models.Model):
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)
    awarage_rating = models.IntegerField("Значение рейтинга")

    class Meta:
        managed = False
        db_table = "movie_rating_view"

moviesite/movies/forms.py
from django import forms

from .models import Reviews, Rating, RatingValue


class ReviewForm(forms.ModelForm):
    """Форма добавления отзыва"""
    class Meta:
        model = Reviews
        fields = ("text", "type")


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    value = forms.ModelChoiceField(
        queryset=RatingValue.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("value",)

moviesite/movies/views.py
from os.path import exists

from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from itertools import chain

from .models import Movie, ReviewTypes, Rating, RatingValue, MovieRatingView, Person, Genre
from .forms import ReviewForm, RatingForm
from .recommendation import recommendation, get_user_ratings


class GenreYear:
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.all().values("year").order_by("year").distinct()


class MovieView(GenreYear, ListView):
    model = MovieRatingView
    template_name = "movies/movie_list.html"
    paginate_by = 5

    def get_queryset(self):
        current_user = self.request.user
        if current_user.id:
            recommendations = recommendation(current_user.id)
            if recommendations is False:
                queryset = MovieRatingView.objects.order_by('-awarage_rating')
            else:
                user_ratings = get_user_ratings(current_user.id)
                queryset1 = MovieRatingView.objects\
                    .filter(Q(id__in=recommendations))\
                    .order_by('-awarage_rating')
                queryset2 = MovieRatingView.objects\
                    .filter(~Q(id__in=recommendations), ~Q(id__in=user_ratings))\
                    .order_by('-awarage_rating')
                queryset3 = MovieRatingView.objects\
                    .filter(~Q(id__in=recommendations), Q(id__in=user_ratings))\
                    .order_by('-awarage_rating')
                queryset = list(chain(queryset1, queryset2, queryset3))
        else:
            queryset = MovieRatingView.objects.order_by('-awarage_rating')
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        return context


class MovieDetailView(GenreYear, DetailView):
    model = Movie
    slug_field = "url"
    template_name = "movies/movie_detail.html"

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        slug = self.kwargs['slug']
        movie = Movie.objects.get(url=slug).id
        current_user = self.request.user
        current_rating = 6
        b = Rating.objects.filter(user_id=current_user.id, movie_id=movie).exists()
        if b:
            current_rating = int(Rating.objects.get(user_id=current_user.id, movie_id=movie).value.value)

        aw_rating = Rating.averageRating(movie)
        context['types'] = ReviewTypes.objects.all()
        context['aw_rating'] = aw_rating
        context['stars'] = RatingValue.objects.all()
        context['current_rating'] = current_rating
        return context


class AddReview(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.movie = movie
            form.user = request.user
            form.save()
        return redirect(movie.get_absolute_url())


class AddRating(View):
    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                movie_id=int(request.POST.get("movie")),
                user_id=int(request.POST.get("user")),
                defaults={'value_id': int(request.POST.get("value"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class FilterMoviesView(GenreYear, ListView):
    template_name = "movies/movie_list.html"

    """Фильтр фильмов в json"""
    def get_queryset(self):
        print(self.request.GET.getlist("year"))
        if len(self.request.GET.getlist("year")) > 0 and len(self.request.GET.getlist("genre")) == 0:
            queryset = MovieRatingView.objects.filter(
                Q(movie__year__in=self.request.GET.getlist("year"))
            ).distinct()
        elif len(self.request.GET.getlist("genre")) > 0 and len(self.request.GET.getlist("year")) == 0:
            queryset = MovieRatingView.objects.filter(
                Q(movie__genres__in=self.request.GET.getlist("genre"))
            ).distinct()
        else:
            queryset = MovieRatingView.objects.filter(
                Q(movie__year__in=self.request.GET.getlist("year")),
                Q(movie__genres__in=self.request.GET.getlist("genre"))
            ).distinct()
        return queryset


class PersonView(GenreYear, DetailView):
    model = Person
    template_name = 'movies/person.html'
    slug_field = 'name'


class Search(ListView):
    template_name = "movies/movie_list.html"

    def get_queryset(self):
        return MovieRatingView.objects.filter(movie__name__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context

moviesite/templates/movies/index.html
{% extends 'index.html' %}
{% block content %}
    {% block breadcrumbs %}
    {% endblock breadcrumbs %}
    <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/_sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
        </div>
    </section>
{% endblock content %}

moviesite/templates/movies/movie_detail.html
{% extends 'movies/index.html' %}

{% block title %} {{ movie.name }} {% endblock title %}

{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block breadcrumbs %}
    <ol class="breadcrumb editContent">
        <li class="breadcrumb-item">
            <a href="/" class="editContent">Домашняя страница</a>
        </li>
        <li class="breadcrumb-item active editContent">{{ movie.name }}</li>
    </ol>
{% endblock breadcrumbs %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ movie.name }}
                </h3>
                <h5 class="editContent">{{ movie.name }}</h5>
                <ul>
                    <li style="list-style: none"><span><b>Год:</b> {{ movie.year }}</span></li>
                    <li style="list-style: none"><span><b>Страна:</b> {{ movie.country }}</span>
                    </li>
                    <li style="list-style: none"><span><b>Слоган:</b> {{ movie.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                                        {% for director in  movie.directors.all %}
                                            <a href="{{ director.get_absolute_url }}" class="editContent">{{ director.name }}</a>
                                        {% endfor %}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span><b>Актеры:</b>
                                        {% for actor in  movie.actors.all %}
                                            <a href="{{ actor.get_absolute_url }}" class="editContent">{{ actor.name }}</a>
                                        {% endfor %}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span><b>Жанр:</b>
                                        {% for genre in  movie.genres.all %}
                                            {{ genre.name }}
                                        {% endfor %}
                                    </span>
                    </li>
                    <li style="list-style: none"><span><b>Премьера в мире:</b> {{ movie.world_premiere }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Бюджет:</b> {{ movie.budget }}</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в США:</b> {{ movie.fees_in_usa }}</span></li>
                    <li style="list-style: none"><span><b>Сборы в мире:</b> {{ movie.fess_in_world }}</span>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <form action="{% url 'add_rating' %}" method="post" name="rating">
                                <b>Ваша оценка:</b>
                                {% csrf_token %}
                                <input type="hidden" name="movie" value="{{ movie.id }}">
                                <input type="hidden" name="user" value="{{ user.id }}">
                                <span class="rating-area">
                                {% for star in stars %}
                                    {% if current_rating <= star.value %}
                                        <input id="rating{{ star.value }}" type="radio" name="value" checked="checked"
                                               value="{{ star.value }}">
                                    {% else %}
                                        <input id="rating{{ star.value }}" type="radio" name="value"
                                               value="{{ star.value }}">
                                    {% endif %}
                                    <label for="rating{{ star.value }}" class="star1 star"></label>
                                {% endfor %}
                            </span>
                            </form>
                        </li>
                    {% endif %}
                    {% if aw_rating %}
                        <li style="list-style: none"><span><b>Средняя оценка:</b> {{ aw_rating }}</span>
                    {% endif %}
                    </li>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            {% if movie.movieshots_set.all.count  != 0 %}
                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                    Кадры из фильма</h3>
                <p>
                    {% for image in movie.movieshots_set.all %}
                        <img src="{{ image.image.url }}" class="img-movie-shots" alt="{{ image.description }}">
                    {% endfor %}
                </p>
            {% endif %}
            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                О фильме {{ movie.name }}</h3>
            <p class="editContent" style="outline: none; cursor: inherit;">{{ movie.synopsis }}</p>
        </div>
        <hr>
        <div class="row">
            {% if user.is_authenticated %}
                <div class="single-form-left" style="width: 60%">
                    <div class="contact-single">
                        <h3 class="editContent" style="outline: none; cursor: inherit;">Оставить отзыв</h3>
                        <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4">
                            {% csrf_token %}
                            <div class="form-group editContent">
                                <label for="contactcomment" class="editContent">
                                    Тип комментария
                                </label>
                                <select class="form-control border" name="type">
                                    {% for type in types %}
                                        <option value="{{ type.id }}">{{ type.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group editContent">
                                <label for="contactcomment" class="editContent">
                                    Ваш комментарий *
                                </label>
                                <textarea class="form-control border" rows="5" name="text"
                                          id="contactcomment" required=""></textarea>
                            </div>
                            <button type="submit"
                                    class="mt-3 btn btn-success btn-block py-3"
                                    style="outline: none; cursor: inherit;">Отправить
                            </button>
                        </form>
                    </div>
                </div>
            {% else %}
                <p style="color: red">Оставлять комментарии могут только авторизованные пользователи</p>
            {% endif %}
        </div>
        {% for review in movie.reviews_set.all %}
            <div class="media py-5">
                <div class="media-body mt-4" style="background-color: {{ review.type.color }}">
                    <h5 class="mt-0 editContent">
                        {{ review.user.username }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
    </div>
{% endblock movie %}

moviesite/templates/movies/movie_list.html
{% extends 'movies/index.html' %}
{% block title %} Кинолист {% endblock title %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in object_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.movie.poster.url }}" class="img-fluid" alt="" style="height: 20em">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.movie.get_absolute_url }}"
                                   class="editContent">{{ movie.movie.name }}</a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">«{{ movie.movie.tagline }}»</span>
                                </div>
                            </div>
                            {% if movie.awarage_rating %}
                            <div class="awarage-rating">
                                Средняя оценка: {{ movie.awarage_rating }}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if page_obj %}
        <div class="pagination" style="width: 100%; margin-top: 30px">
            <span class="step_links" style="margin-left: 20%">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; первая</a>
                    <a href="?page={{ page_obj.previous_page_number }}">назад</a>
                {% endif %}
                <span class="current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">вперед</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
    </div>
{% endblock movie %}

moviesite/templates/movies/person.html
{% extends 'movies/index.html' %}

{% block title %} {{ person.name }} {% endblock title %}

{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ person.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ person.name }}
                </h3>
                <h5 class="editContent">{{ person.name }}</h5>
                <ul>
                    <li style="list-style: none"><span><b>Дата рождения:</b> {{ person.birthdate }}</span></li>
                                        {% if person.film_director.all %}
                    <li style="list-style: none">
                        <span><b>Режиссер:</b>
                            {% for movie in  person.film_director.all %}
                                <a href="{{ movie.get_absolute_url }}" class="editContent">{{ movie.name }}</a>
                            {% endfor %}
                        </span>
                    </li>
                    {% endif %}
                    {% if person.film_actor.all %}
                    <li style="list-style: none">
                        <span><b>Актер:</b>
                            {% for movie in  person.film_actor.all %}
                                <a href="{{ movie.get_absolute_url }}" class="editContent">{{ movie.name }}</a>
                            {% endfor %}
                        </span>
                    </li>
                    {% endif %}
            </div>
        </div>
        <div>
            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                Краткая биография</h3>
            <p class="editContent" style="outline: none; cursor: inherit;">{{ person.biography }}</p>
        </div>
        <hr>
    </div>
    </div>
{% endblock movie %}